### ISSUE TITLE
失效了，没用了？

### ISSUE THREAD

**Issue by tyhisyourfather** [FrankTiao/sms-boom-go#1]
![J320ARIQC7HD3W RFLSUZ3T](https://user-images.githubusercontent.com/112569749/192072645-788122f4-d9bf-42c3-9787-615e692c9001.png)

**Comment by FrankTiao** [comment]
> ![J320ARIQC7HD3W RFLSUZ3T](https://user-images.githubusercontent.com/112569749/192072645-788122f4-d9bf-42c3-9787-615e692c9001.png)

请检查下手机号码格式是否正确

方便的话提供下错误日志。
日志文件位置：`C:\Users\{用户名}\sms-boom-go\logs\{日期}\{小时}.log`
