### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by SuperManYY** [FrankTiao/sms-boom-go#2]
![图片](https://user-images.githubusercontent.com/60775692/195979701-2e5a9512-516e-4999-aba5-6628f66fe514.png)
![图片](https://user-images.githubusercontent.com/60775692/195979731-a2d69a12-df34-4923-a47b-4dfc2b80b9db.png)

**Comment by FrankTiao** [comment]
> ![图片](https://user-images.githubusercontent.com/60775692/195979701-2e5a9512-516e-4999-aba5-6628f66fe514.png) ![图片](https://user-images.githubusercontent.com/60775692/195979731-a2d69a12-df34-4923-a47b-4dfc2b80b9db.png)

已收到反馈，正在排查

**Comment by FrankTiao** [comment]
> ![图片](https://user-images.githubusercontent.com/60775692/195979701-2e5a9512-516e-4999-aba5-6628f66fe514.png) ![图片](https://user-images.githubusercontent.com/60775692/195979731-a2d69a12-df34-4923-a47b-4dfc2b80b9db.png)

BUG已修复，请下载最新的客户端：https://github.com/FrankTiao/sms-boom-go/releases/tag/v1.0.2

**Comment by FrankTiao** [comment]
BUG已修复，请下载最新的客户端：https://github.com/FrankTiao/sms-boom-go/releases/tag/v1.0.2
若无问题，此issues即将关闭 @SuperManYY
