### ISSUE TITLE
运行go run main.go报错 

### ISSUE THREAD

**Issue by GadouLee** [FrankTiao/sms-boom-go#4]
../../go/pkg/mod/github.com/mattn/go-runewidth@v0.0.13/runewidth.go:6:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /Users/lichangcheng/go/pkg/mod/github.com/rivo/uniseg@v0.3.4

**Comment by GadouLee** [comment]
你应该写一个 运行步骤，和依赖按照，小白不是很懂这种报错

**Comment by FrankTiao** [comment]
> 

小白建议直接使用编译好的可执行文件，下载链接[在这里](https://github.com/FrankTiao/sms-boom-go/releases)

<br />

需要修改代码参考如下步骤执行：
```
$ git clone https://github.com/FrankTiao/sms-boom-go.git
$ cd sms-boom-go
$ go mod tidy
$ go run main.go
```
- golang版本需要1.18
