### ISSUE TITLE
大佬，我想问一下如何自行的去添加一些短信的端口

### ISSUE THREAD

**Issue by cdyinthe** [FrankTiao/sms-boom-go#6]
rt

**Comment by FrankTiao** [comment]
目前版本中用户无法自行添加短信接口
**但可以通过修改代码实现，需要一定的编程基础，具体修改方式如下**

## 一、接口类型
第三方接口目前分为两类：
1. api地址与参数都在一条url上的GET请求，例如：`http://xxxxx.com/basis/sendCheckCode?mobile=[phone]`
2. 需要在请求头中需要携带一些特定参数，例如Cookie的复杂接口，例如：
```
{
    "desc": "彩xxx",
    "url": "https://xxx.com/v1/send_sms_code",
    "method": "POST",
    "header": {
        "Referer": "https://xxx.com/",
        "Cy-Token": "token 9876032166"
    },
    "data": {
        "phone_num": "[phone]",
        "area_code": "86"
    }
}
```
以上两种接口类型可以根据自定义的接口自行选择

### 字段说明
|  字段名   | 必须  | 类型 |.说明 | 示例 |
|  ----  | ----  |----  |----  |---  |
| desc  | 是 | string |  接口说明 | github |
| url  | 是 | string |  接口地址 | http://xxx.com/ |
| method  | 是 | string |  请求方式 | GET/POST |
| header  | 是 | string |  请求头，没有时可以为空字符串 | 参考上面的示例 |
| data  | 是 | string|  请求参数，没有时可以为空字符串|参考上面的示例 |


## 二、占位符
占位符相当于一个变量，作用是在程序执行时将该占位符替换为指定的值。
例如，上面的示例中存在一个占位符`[phone]`，在运行时将会被替换为下面这个样子：
```
http://xxxxx.com/basis/sendCheckCode?mobile=[phone]
http://xxxxx.com/basis/sendCheckCode?mobile=13600000000
```
### 目前支持的占位符：
|  字段名   | 说明 | 示例 |
|  ----  | ----  |---  |
| [phone]  |  手机号 | 13600000000 |
|[timestamp]  |  秒级时间戳| 1666363178 |

若以上占位符不满足你的需求，你可以在[boom/api.go:113](https://github.com/FrankTiao/sms-boom-go/blob/5f653efb2dc250f80ca2cc663094eb1790ed9d38/boom/api.go#L113)添加自己的逻辑


## 三、添加自己的接口
1. 在boom/api.go中定义自己的接口：
```
// 复杂类型接口
var customApis = []Api{
	{
		Desc:   "xxx",
		Url:    "xxx",
		Method: "xxx",
		Header: "", // 此处可以为空字符串
		Data:   "{\"phone_num\": \"[phone]\", \"area_code\": \"86\" }", // 不为空时需要是一个合法的JSON字符串
	},
}

// 简单的GET请求接口
var customGetApis = []string{
	"http://xxxxx.com/basis/sendCheckCode?mobile=[phone]",
}
```

2. 在加载接口时将自定义接口追加进去
- 复杂接口：[boom/api.go:129](https://github.com/FrankTiao/sms-boom-go/blob/5f653efb2dc250f80ca2cc663094eb1790ed9d38/boom/api.go#L129)
```
func loadApi() (*[]Api, error) {
	// ...省略相关代码
	var apis []Api
	err = json.Unmarshal(content, &apis)
	if err != nil {
		return nil, err
	}

         // 追加自定义接口
	apis = append(apis, customApis...)

	// ...省略相关代码
}
```

- 简单GET接口：[boom/api.go:160](https://github.com/FrankTiao/sms-boom-go/blob/5f653efb2dc250f80ca2cc663094eb1790ed9d38/boom/api.go#L160)
```
func loadGetApi() (*[]string, error) {
	// ...省略相关代码

	var apis []string
	err = json.Unmarshal(content, &apis)
	if err != nil {
		return nil, err
	}

	// 追加自定义接口
	apis = append(apis, customGetApis...)

	// ...省略相关代码
}
```

## 四、最后
执行 go run main.go 或 go build 运行即可

**Comment by FrankTiao** [comment]
最最后，求个star~😄
